### ISSUE TITLE
[Errno 111]Connection refused

### ISSUE THREAD

**Issue by jibanli** [f0lg0/Oncogene#1]
![error111](https://user-images.githubusercontent.com/39478794/82578565-1fa22400-9bbf-11ea-8800-d2b8889e5b53.png)

**Comment by jibanli** [comment]
Hi. I used mininet on ubuntu and build a topo which two hosts connected to a switch.

**Comment by f0lg0** [comment]
@jibanli 
did you modify the server address inside clientlinux.py? Also check /etc/hosts and make sure there's a real IP address assigned to your machine and not something like 127.0.0.1

for example:

127.0.0.1 localhost (OK)
10.0.1.50 mymachine

**Comment by jibanli** [comment]
reply really fast...

**Comment by f0lg0** [comment]
@jibanli 
please paste the output of /etc/hosts
The application should work, check your network configuration. Also make sure everything is set correctly in clientlinux.py
I've never used mininet before

**Comment by jibanli** [comment]
![etc_hosts1](https://user-images.githubusercontent.com/39478794/82579657-b58a7e80-9bc0-11ea-90f7-7ddb583b470d.png)

**Comment by jibanli** [comment]
![mininet_](https://user-images.githubusercontent.com/39478794/82580049-3a759800-9bc1-11ea-88c8-10723b0050f3.png)

**Comment by f0lg0** [comment]
@jibanli 
If aa-virtual-machine is the server as I said you need to put a real address at the line

127.0.0.1 aa-virtual-machine

in aa-virtual-machine run something like "ifconfig" or "ip a", grab the address of the machine and replace 127.0.0.1 with that.

for example:

10.0.1.50 aa-virtual-machine

like so your server will start on that address and you will be able to connect to it!
Let me know if it works!

It's important that the address is the same as the one you grabbed with ifconfig/ip a

**Comment by jibanli** [comment]
wait me a moment please...

**Comment by jibanli** [comment]
![hosts_2](https://user-images.githubusercontent.com/39478794/82581585-5e39dd80-9bc3-11ea-9560-253aefac9a8b.png)

**Comment by jibanli** [comment]
https://stackoverflow.com/questions/19246103/socket-errorerrno-99-cannot-assign-requested-address-and-namespace-in-python

**Comment by jibanli** [comment]
I found the link above... But do not know how to do...

**Comment by f0lg0** [comment]
@jibanli 
It means that it can't use that address. Make sure its a valid one, grabbed from "ip a" or "ifconfig" in aa-virtual-machine. Also make sure the port is free. You could also try to bind 0.0.0.0 in oncogene.py; that means "listen on every ip of this machine". But if that IP in etc/hosts is wrong then the problem will persist.

**Comment by jibanli** [comment]
![ifconfig1](https://user-images.githubusercontent.com/39478794/82583640-df926f80-9bc5-11ea-9970-1241ffb703fa.png)

**Comment by f0lg0** [comment]
@jibanli
I actually don't know what is going on, it should have fixed it. It's something with your network configuration. I did all the possible sorry. Last thing you could try is to bind at 0.0.0.0 in oncogene.py (in the server class theres an option called bind(), replace the value with 0.0.0.0).
If you have a firewall make sure to allow port 1234. I don't know much about networks especially mininet.
Good luck!

**Comment by jibanli** [comment]
Thanks for your patient reply. I will try it...

**Comment by jibanli** [comment]
![host_0_0](https://user-images.githubusercontent.com/39478794/82587398-b2e15680-9bcb-11ea-9252-8b48ee340a99.png)

**Comment by f0lg0** [comment]
@jibanli 
Awesome! No need to thank me, thank you for using Oncogene! Fell free to @ me if you need.

**Comment by jibanli** [comment]
I changed the IP  address in /etc/hosts to 0.0.0.0.  And I succeeded in solving the problem.
Sorry I did not read the code 'Oncogene' carefully before. And I am unfamiliar with linux /etc/hosts.
I wanted to find some tools to produce realtime network traffic in SDN simulation environment and found this.
It is 1:41 time in Beijing. I will go to sleep...

**Comment by f0lg0** [comment]
@jibanli 
Good job! I'm so happy because my work reached you in Beijing! So fascinating. Italian developer here :)
